# Module will prolly be abandoned as IMDB is expensive, I don't have an encyclopedia at hand as encyclopedia.com is
# not on download and wikipedia is only downloadable in html, the getty isn't dowloadble either...
